解决Windows编译问题 #11
cloudwego/volo pull request #29
Opened 2022-09-08 06:06 UTC by anwentec

![运行测试程序](https://user-images.githubusercontent.com/101235513/189046702-972407c3-2124-4172-ab34-10c3300d5761.png)

## Motivation

## Solution

2022-09-08 06:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudwego/volo?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cloudwego/volo?pullRequest=29) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Jason<br/>:x: anwentec<br/><hr/>**Jason** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudwego/volo?pullRequest=29) it.</sub>

2022-09-08 06:30 UTC, PureWhiteWu requested changes
你好，非常感谢你的贡献！
总体来说思路没问题，不过仍有一些需要修改的地方。
条件编译其实是语句级别的，因此不需要把所有的实现都复制一份，这样后续也很难维护，比如可以只针对 enum 中的某个 variant 做条件编译，以及对 match 中的某个分支做条件编译，这样可以大大减少重复的代码。
另外，可以采用 [target_family](https://doc.rust-lang.org/reference/conditional-compilation.html#target_family) 进行判断，target_family 要比 target_os 更适合这个场景。

2022-09-08 06:30 UTC, PureWhiteWu commented on volo/src/net/incoming.rs
>      Unix(#[pin] UnixListenerStream),
`#[cfg(target_family = "unix")]`可以放在这一行上就行，不需要单独拷贝一份 enum 出来？其它地方也是一样。

2022-09-08 09:09 UTC, anwentec commented on volo/src/net/incoming.rs
>      Unix(#[pin] UnixListenerStream),
是的，这样看起来舒服多了

2022-09-08 10:30 UTC, PureWhiteWu requested changes
很棒，还有一些小的地方可以优化一下～
另外，可以把 ci 里面的 windows 部分取消注释，让 ci 跑一下 windows 的测试看看～

2022-09-08 10:30 UTC, PureWhiteWu commented on volo-thrift/src/server.rs
> +        #[cfg(target_family = "unix")]
这三个初始化是不是可以挪到下面的 tokio::select! 一起？
可以放在一个大的 block 中，就可以只写一个 #[cfg(target_family = "unix")] 了，比如这样：
```rust
#[cfg(target_family = "unix")]
{
        let mut sigint = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::interrupt())?;
        let mut sighup = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::hangup())?;
        let mut sigterm = tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())?;
        tokio::select! {
                ...
        }
}
```

2022-09-08 10:30 UTC, PureWhiteWu commented on volo/src/net/incoming.rs
> +}
no newline at end of file

2022-09-08 16:20 UTC, LYF1999 commented on volo-thrift/src/transport/pool/mod.rs
> +        net::TcpStream,
we can delete this mod 
https://github.com/cloudwego/volo/blob/cd30b987e88a5f5043d02945ab64c64fe27bb025/volo-thrift/src/transport/pool/mod.rs#L612-L626

2022-09-08 17:51 UTC, PureWhiteWu commented
非常棒，还有一些 lint 的问题和 cla 的问题需要解决一下，就可以啦～

2022-09-09 15:57 UTC, anwentec commented
我本地git配置的阿里云的云效git，所以Jason用户提交的commit，我也不知道怎么签署CLA.非常抱歉

2022-09-10 01:23 UTC, anwentec commented
我可以删除我fork的库，然后重新fork，配置好anwenteck这个账号后，再提交commit,是否可行？

2022-09-10 08:34 UTC, closed without merging