fix: grpc middleware error constraints
cloudwego/volo pull request #33
Opened 2022-09-16 03:06 UTC by Millione

Allow middleware to return self-defined error type

2022-09-16 03:15 UTC, LYF1999 commented on volo-grpc/src/server/mod.rs
> +    S::Error: Into<BoxError>,
`Into<Status>` 会更好嘛？

2022-09-16 03:21 UTC, LYF1999 submitted a review, later dismissed

2022-09-16 03:23 UTC, PureWhiteWu requested changes
不应该这么做，因为我们返回给上游的需要是一个 Status

2022-09-19 04:09 UTC, raaay0608 commented
看了下，目前规约是要求实现 `Into<BoxError>`
参考：https://github.com/cloudwego/volo/blob/af0ff5caa097ec7bdd514c9a9d330bfcee3a6abf/volo-grpc/src/status.rs#L338
对于纯粹自定义的错误类型，会以 UNKNOWN 为 status code 进行返回，我也认为是不合适的，问题可能包括：
- caller 难以判断是否可以重试
- caller 难以决定后续行为（e.g. 调用服务有鉴权 middleware，对于鉴权失败和其他错误，caller 需要有不同的处理方式）
- 监控信息量不足，业务难以排查问题
- 给长期服务治理带来麻烦和成本
- ......

因而，对于有拦截作用的 middleware，其应在其所支持的协议下，均明确指定 status code（并最好强迫所有 middleware 都要这么做，避免滥用 UNKNOWN）。从这个角度考虑，middleware 也一定需要与服务协议存在耦合，无法避免。

我想法是，以下方法二选一，并后续在 grpc/thrift 之间尽可能保持一致（一下以 grpc 为例）：
1. 修改 `S::Error` 为 `Into<Status>`（方法签名变化，breaking change）
2. 保持 volo/volo-grpc 主框架不动，middleware 内负责执行 `.into()`（会增加一些 middleware 开发难度，我拼对模版参数也确实是花了些时间的）

2022-09-19 06:04 UTC, Millione commented
> 看了下，目前规约是要求实现 `Into<BoxError>` 参考：
> 
> https://github.com/cloudwego/volo/blob/af0ff5caa097ec7bdd514c9a9d330bfcee3a6abf/volo-grpc/src/status.rs#L338
> 
> 
> 对于纯粹自定义的错误类型，会以 UNKNOWN 为 status code 进行返回，我也认为是不合适的，问题可能包括：
> * caller 难以判断是否可以重试
> * caller 难以决定后续行为（e.g. 调用服务有鉴权 middleware，对于鉴权失败和其他错误，caller 需要有不同的处理方式）
> * 监控信息量不足，业务难以排查问题
> * 给长期服务治理带来麻烦和成本
> * ......
> 
> 因而，对于有拦截作用的 middleware，其应在其所支持的协议下，均明确指定 status code（并最好强迫所有 middleware 都要这么做，避免滥用 UNKNOWN）。从这个角度考虑，middleware 也一定需要与服务协议存在耦合，无法避免。
> 
> 我想法是，以下方法二选一，并后续在 grpc/thrift 之间尽可能保持一致（一下以 grpc 为例）：
> 
> 1. 修改 `S::Error` 为 `Into<Status>`（方法签名变化，breaking change）
> 2. 保持 volo/volo-grpc 主框架不动，middleware 内负责执行 `.into()`（会增加一些 middleware 开发难度，我拼对模版参数也确实是花了些时间的）

@raaay0608 赞，目前暂定的是按方案1进行修复

2022-09-21 09:39 UTC, LYF1999 approved these changes

2022-09-21 09:41 UTC, PureWhiteWu approved these changes

2022-09-21 09:49 UTC, merged